// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj_anGXx5OxQTfOHgi4l_ehnR-9R19bNc',
    appId: '1:135979821993:web:a4c7614fdd310ef862f2b8',
    messagingSenderId: '135979821993',
    projectId: 'class-room-b7ecf',
    authDomain: 'class-room-b7ecf.firebaseapp.com',
    storageBucket: 'class-room-b7ecf.appspot.com',
    measurementId: 'G-9S9Y6JRPQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHfsfFiA2i_Qz0QfmWPpJ5yskmyh66kYk',
    appId: '1:135979821993:android:97ea823b32a7c90262f2b8',
    messagingSenderId: '135979821993',
    projectId: 'class-room-b7ecf',
    storageBucket: 'class-room-b7ecf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL-vR4xru5v1triuqzjBJs74bwNWJAU84',
    appId: '1:135979821993:ios:3b940506d967303962f2b8',
    messagingSenderId: '135979821993',
    projectId: 'class-room-b7ecf',
    storageBucket: 'class-room-b7ecf.appspot.com',
    iosClientId: '135979821993-9dtbkcab83u8bd1m4qusacgauqdi838j.apps.googleusercontent.com',
    iosBundleId: 'com.example.classRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL-vR4xru5v1triuqzjBJs74bwNWJAU84',
    appId: '1:135979821993:ios:412e9bb23960112062f2b8',
    messagingSenderId: '135979821993',
    projectId: 'class-room-b7ecf',
    storageBucket: 'class-room-b7ecf.appspot.com',
    iosClientId: '135979821993-7fqn1s75v4uh1jfe77h2vfic2rp225i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.classRoom.RunnerTests',
  );
}
